{% set name = "zc.buildout" %}
{% set version = "2.13.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac6edd48b1d7b1fba383dd0840fd49c53266f6bd426111a0195bcc640f4aff0f

build:
  number: 1
  entry_points:
    - buildout=zc.buildout.buildout:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools >=8.0,<52

test:
  imports:
    - zc
    - zc.buildout
  commands:
    - buildout --help

about:
  home: http://buildout.org
  license: ZPL-2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: System for managing development buildouts
  doc_url: http://www.buildout.org/en/latest/
  dev_url: https://github.com/buildout/buildout

extra:
  recipe-maintainers:
    - 183amir
    - lcolbois
