{% set name = "zc.buildout" %}
{% set version = "2.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 422724f6ec8eeea5ee3527a33d5b90fc1dc3a29f68a42e2119785d5ac516d4b8

build:
  number: 0
  entry_points:
    - buildout=zc.buildout.buildout:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=8.0,<52
  run:
    - python
    - setuptools >=8.0,<52

test:
  imports:
    - zc
    - zc.buildout
  commands:
    - buildout --help

about:
  home: http://buildout.org
  license: ZPL-2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: System for managing development buildouts
  doc_url: http://www.buildout.org/en/latest/
  dev_url: https://github.com/buildout/buildout

extra:
  recipe-maintainers:
    - 183amir
    - lcolbois
